config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'kittens#index'
  
  get 'kittens/index'
  get 'kittens/show'
  get 'kittens/new'
  get 'kittens/edit'
  
  get 'pages/info'
  get 'pages/gallery'
  
  resource :kittens
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
# frozen_string_literal: true

class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/kittens_controller.rb
# frozen_string_literal: true

# require 'flickr'

class KittensController < ApplicationController
  def index
    flickr = Flickr.new

    @kittens = Kitten.all

    paramaters = { flickr: flickr,
                   user_id: '',
                   search_text: 'kittens',
                   tags: 'cute, cat, kittens',
                   extras: 'date_taken, owner_name',
                   size: 4 }

    @kitten_photos = get_flickr_photos(paramaters)

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find_by(id: params[:id]) || Kitten.first

    respond_to do |format|
      format.json { render json: @kitten }
      format.html
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(name: params[:kitten][:name],
                         age: params[:kitten][:age],
                         cuteness: params[:kitten][:cuteness],
                         softness: params[:kitten][:softness])
    if @kitten.save
      flash[:success] = 'Kitten created!'
      redirect_to kittens_path(id: @kitten.id)
    else
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find_by(id: params[:id])
  end

  def update
    @kitten = Kitten.find_by(id: params[:id])

    permitted = params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    if @kitten.update_attributes(permitted)
      flash[:success] = 'Kitten edited!'
    else
      flash[:warning] = 'Kitten did not update'
    end

    redirect_to kittens_path(id: @kitten.id)
  end

  def destroy
    @kitten = Kitten.find_by(id: params[:id])
    @kitten.destroy
    flash[:success] = 'Kitten deleted!'
    redirect_to root_url
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def info
    flickr = Flickr.new
    return unless params[:search] || params[:user_id]

    input = params[:user_id] || params[:search][:input]

    @people = input.match(/\d*@\S*/) ? get_flickr_user_by_id(flickr, input) : get_flickr_user_by_name(flickr, input)

    paramaters = { flickr: flickr,
                   user_id: @people.id,
                   search_text: '',
                   tags: '',
                   extras: 'date_taken, owner_name',
                   size: 99 }

    @photos = get_flickr_photos(paramaters)
  end

  def gallery; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def get_flickr_photos(paramaters)
    photos = []
    urls = 'url_q,'

    if !paramaters[:search_text].empty?
      photo_lists = paramaters[:flickr].photos.search(text: paramaters[:search_text],
                                                      tags: paramaters[:tags],
                                                      extras: urls + paramaters[:extras],
                                                      per_page: paramaters[:size],
                                                      privacy_filter: 1)
    elsif !paramaters[:user_id].empty?
      photo_lists = paramaters[:flickr].people.getPhotos(user_id: paramaters[:user_id],
                                                         extras: urls + paramaters[:extras],
                                                         per_page: paramaters[:size],
                                                         privacy_filter: 1)
    end

    photo_lists.each do |list|
      photo = { title: list.title[0..50],
                owner_id: list.owner,
                url: list.url_q,
                date_taken: list.datetaken,
                owner_name: list.ownername }
      photos << photo
    end

    photos
  end

  def get_flickr_user_by_id(flickr, id)
    flickr.people.getInfo(user_id: id)
  end

  def get_flickr_user_by_name(flickr, name)
    user_id = flickr.people.findByUsername(username: name).id
    flickr.people.getInfo(user_id: user_id)
  end
end

app/helpers/kittens_helper.rb
# frozen_string_literal: true

module KittensHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/kittens/_footer_link.html.erb
<p class="my-5">
  <%= link_to "Back to Home", root_url %>
</p>

app/views/kittens/_form.html.erb
<%= form_for(@kitten, url: kittens_path(id: @kitten.id)) do |f| %>
    <div class="row">
      <div class="form-group col-md-3"> 
      Kitten's name: <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group col-md-3"> 
        Age: <%= f.number_field :age,in: 1..30, step: 0.5, class: "form-control" %>
      </div>
      <div class="form-group col-md-3"> 
        Cuteness: <%= f.number_field :cuteness, in: 0..10, step: 0.5, class: "form-control" %>
      </div>
      <div class="form-group col-md-3"> 
        Softness: <%= f.number_field :softness, in: 0..10, step: 0.5, class: "form-control" %>
      </div>
    </div>


    <div class="actions">
      <%= f.submit "Update", class: "btn btn-primary post_button"  %>
    </div>
<%end %>

app/views/kittens/_kitten.html.erb
<tr>
      <th scope="row"> <%= kitten.id %> </th>
      <td><%= kitten.name %></td>
      <td><%= kitten.age %></td>
      <td><%= kitten.cuteness %></td>
      <td><%= kitten.softness %></td>
      <td>
            <%= link_to 'Show', kittens_show_path(id: kitten.id), class: "mr-2" %>
            <%= link_to 'Edit', edit_kittens_path(id: kitten.id), class: "mr-2 text-info" %>
            <%= link_to 'Delete', kittens_path(id: kitten.id), method: :delete, data: {confirm: "Are you sure?"}, class: "mr-2 text-danger" %>
      </td>

</tr>
    

app/views/kittens/edit.html.erb
<h1>Edit Kitten's info </h1>

<%= render 'form' %>

<%=  render 'footer_link'%>

app/views/kittens/index.html.erb
<h1>Welcome to Kittens World</h1>

<div class="card-deck my-5">

<% if @kitten_photos %>  
  <% @kitten_photos.each do |photo| %>
    <div class="card">
      <%= image_tag photo[:url], class: "card-img-top", alt: "Kittens" %>
      <div class="card-body">
        <h5 class="card-title"> <%= photo[:title] %> </h5>
          <p class="card-text"> <b> By: </b> <%= link_to photo[:owner_name], pages_info_path(user_id: photo[:owner_id]) %> </p>
          <p class="card-text">
            <small class="text-muted">
              Photo Taken <%= time_ago_in_words(photo[:date_taken])  %> ago.
            </small>
          </p>
      </div>
    </div>
  <% end %>
<% end %>
</div>

<h1 class="font-italic my-5">Find Your Favorite People in Flickr !!!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 mx-auto">
    <div class="form-group">
      <%= form_for(:search, url: pages_info_path, method: :get) do |f| %>
        <%= f.text_field :input, class: 'form-control', placeholder: "Try 24448805@N07 or Tim Downey", value: "24448805@N07", label: "input" %>
        <small id="searchHelpBlock" class="form-text text-muted">
            Find Flickr User by id (Try '24448805@N07') or username (Try 'Tony Schi Photos').
        </small>
        <%= f.submit "Find User", class: "btn btn-info my-3" %>
      <% end %>
    </div>
  </div>
</div>

<hr class="my-4">

<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Cuteness</th>
        <th scope="col">Softness</th>
        <th scope="col">Operation</th>
      </tr>
    </thead>
    <tbody>
      <%= render @kittens %>
    </tbody>
  </table>

  <hr>
    <div class="container my-3">
        <%= link_to 'Input New Kitten', new_kittens_path, class: "btn btn-primary" %>
    </div>

</div>

app/views/kittens/new.html.erb
<h1>Update A Kitten's info</h1>

<%=  render 'form' %>

<%=  render 'footer_link'%>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<p>Find out more about me here!</p>

<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to 'Delete', kittens_path(@kitten), method: :delete, data: {confirm: "Are you sure?"}, class: "mr-2 btn btn-danger" %>

<%=  render 'footer_link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    
    <div class="container mt-5 text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/gallery.html.erb
<h1>Pages#gallery</h1>
<p>Find me in app/views/pages/gallery.html.erb</p>

app/views/pages/info.html.erb
<h1 class="text-center my-5">User Info Page</h1>

<% if @people %>
  <div class="row">
      <div class="col-md-6 col-md-offset-3 mx-auto">
        <p class="text-left">User Name: <%= link_to @people.username, @people.profileurl %> </p>
        <% if @people.methods.include?(:realname) %>
          <p class="text-left">Real Name: <%= @people.realname %> </p>
        <% end %>
        <p class="text-left">User ID: <%= @people.id %> </p>
        <p class="text-left">Total Public Photos: <%= link_to @people.photos.count, @people.photosurl %></p>
        <% if @people.methods.include?(:location) %>
          <p class="text-left">From: <%= @people.location %> </p>
        <% end %>
    </div>
  </div>

  <% if @photos %>
    <div class="container">

      <h2 class="font-weight-light text-center text-uppercase mt-4 mb-0 "> <%= @people.username %> 's Gallary</h2>

      <hr class="mt-2 mb-5">

      <div class="row text-center text-lg-left">

      <% @photos.each do |photo| %>

        <div class="col-lg-3 col-md-4 col-6">
          <a href=<%= photo[:url] %> class="d-block mb-4 h-100">
            <%= image_tag photo[:url], class: "img-fluid img-thumbnail", alt: "gallary" %>
        </div>

      <% end %>

      </div>

    </div>

  <% end %>
<% else %>
  <h3 class="text-center my-5">No Such User, Please try again!</h3>
<% end %>